var keystone = require('keystone'),
    Types = keystone.Field.Types;
 
var Project = new keystone.List('Project');
 
Project.add({
    title: { type: String, initial: true, required: true, index: true },
    year: { type: Number, required: true, wysiwg: true, height: 400, initial: true },
    cover: { type: Types.Relationship, ref: 'Photo', required: true, initial: true },
    description: { type: Types.Html, initial: true },
    photoCount: { type: Number, required: true, initial: true },
    student1: { type: Types.Relationship, ref: 'Student', initial: true },
    student2: { type: Types.Relationship, ref: 'Student', initial: true },
    student3: { type: Types.Relationship, ref: 'Student', initial: true },
    student4: { type: Types.Relationship, ref: 'Student', initial: true },
    student5: { type: Types.Relationship, ref: 'Student', initial: true },
    student6: { type: Types.Relationship, ref: 'Student', initial: true },
    student7: { type: Types.Relationship, ref: 'Student', initial: true },
    student8: { type: Types.Relationship, ref: 'Student', initial: true },
    student9: { type: Types.Relationship, ref: 'Student', initial: true },
    student10: { type: Types.Relationship, ref: 'Student', initial: true },
    student11: { type: Types.Relationship, ref: 'Student', initial: true },
    student12: { type: Types.Relationship, ref: 'Student', initial: true },
    student13: { type: Types.Relationship, ref: 'Student', initial: true },
    student14: { type: Types.Relationship, ref: 'Student', initial: true },
    student15: { type: Types.Relationship, ref: 'Student', initial: true },
    student16: { type: Types.Relationship, ref: 'Student', initial: true },
    student17: { type: Types.Relationship, ref: 'Student', initial: true },
    student18: { type: Types.Relationship, ref: 'Student', initial: true },
    student19: { type: Types.Relationship, ref: 'Student', initial: true },
    student20: { type: Types.Relationship, ref: 'Student', initial: true },
    photo1: { type: Types.Relationship, ref: 'Photo', initial: true },
    photo2: { type: Types.Relationship, ref: 'Photo', initial: true },
    photo3: { type: Types.Relationship, ref: 'Photo', initial: true },
    photo4: { type: Types.Relationship, ref: 'Photo', initial: true },
    photo5: { type: Types.Relationship, ref: 'Photo', initial: true },
    photo6: { type: Types.Relationship, ref: 'Photo', initial: true },
    photo7: { type: Types.Relationship, ref: 'Photo', initial: true },
    photo8: { type: Types.Relationship, ref: 'Photo', initial: true },
    photo9: { type: Types.Relationship, ref: 'Photo', initial: true },
    photo10: { type: Types.Relationship, ref: 'Photo', initial: true },
    photo11: { type: Types.Relationship, ref: 'Photo', initial: true },
    photo12: { type: Types.Relationship, ref: 'Photo', initial: true },
    photo13: { type: Types.Relationship, ref: 'Photo', initial: true },
    photo14: { type: Types.Relationship, ref: 'Photo', initial: true },
    photo15: { type: Types.Relationship, ref: 'Photo', initial: true },
    photo16: { type: Types.Relationship, ref: 'Photo', initial: true },
    photo17: { type: Types.Relationship, ref: 'Photo', initial: true },
    photo18: { type: Types.Relationship, ref: 'Photo', initial: true },
    photo19: { type: Types.Relationship, ref: 'Photo', initial: true },
    photo20: { type: Types.Relationship, ref: 'Photo', initial: true },
    photo21: { type: Types.Relationship, ref: 'Photo', initial: true },
    photo22: { type: Types.Relationship, ref: 'Photo', initial: true },
    photo23: { type: Types.Relationship, ref: 'Photo', initial: true },
    photo24: { type: Types.Relationship, ref: 'Photo', initial: true },
    photo25: { type: Types.Relationship, ref: 'Photo', initial: true }
});
 
Project.register();
